//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAccountBook_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class AccountBook
    {
        public System.Guid Id { get; set; }
        public int Categoryyy { get; set; }

        [Remote("MoneyValid", "Valid", ErrorMessage = "金額只能輸入正整數")]
        [Display(Name = "金額")]
        [DisplayFormat(DataFormatString = "{0:N0}")]
        public int Amounttt { get; set; }

        [Remote("DateValid", "Valid", ErrorMessage = "日期不得大於今天")]
        [Display(Name = "日期")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime Dateee { get; set; }

        [Remote("RemarkValid", "Valid", ErrorMessage = "備註最多100個字元")]
        [Display(Name = "備註")]
        public string Remarkkk { get; set; }
    }
}
